### PR TITLE
Switch from `bitness` to `architecture`

### PR DESCRIPTION
**Pull request by dennisameling**
Needs https://github.com/git-for-windows/build-extra/pull/462 to be merged first

As we're [moving away](https://github.com/git-for-windows/git/discussions/4203) from `bitness` in favor of `architecture`, let's update the logic in `setup-git-for-windows-sdk` as well. This also adds support for `aarch64` in `create-sdk-artifact`, which we couldn't do with `bitness`.

### CODE REVIEW

**Comment by dscho** [comment]
@dennisameling do we need anything else to support `build-installers`/`aarch64` in this Action? If not, I'll gladly release v1.8.0 with the news!

**Comment by dennisameling** [comment]
Theoretically speaking, everything _should_ work now. [Let's test](https://github.com/git-for-windows/git-for-windows-automation/actions/runs/4106894298)!

**Comment by dennisameling** [comment]
Doh. Completely overlooked the block we had in place for all "non-full" flavors of the arm64 SDK. [Let's get rid of that](https://github.com/git-for-windows/setup-git-for-windows-sdk/pull/592).

**Comment by dennisameling** [comment]
> @dennisameling do we need anything else to support `build-installers`/`aarch64` in this Action? If not, I'll gladly release v1.8.0 with the news!

[It's working now](https://github.com/git-for-windows/git-for-windows-automation/actions/runs/4108411699/jobs/7089072793)! 🚀 The `build-installers` artifact was created successfully. It looks like the `sync` job in `git-sdk-arm64` still needs to do its thing as the pipeline tried to update `msys2-runtime` which closed the process... 🤦🏼 we might want to move the logic from the new SDK's `sync` pipeline into the [automation repo's `build-and-deploy` pipeline too](https://github.com/git-for-windows/git-for-windows-automation/blob/c701662ff6838bea2ff4fccccf73df3b2af95605/.github/workflows/build-and-deploy.yml#L160, but that's unrelated to this change in `setup-git-for-windows-sdk`.

So it looks like the new version of the Action is ready to be published at least! 😊

**Comment by dscho** [comment]
> Theoretically speaking, everything _should_ work now. [Let's test](https://github.com/git-for-windows/git-for-windows-automation/actions/runs/4106894298)!

Darn. https://github.com/git-for-windows/git-for-windows-automation/actions/runs/4108411699/jobs/7089072793#step:10:482 means that `git-sdk-arm64` needs to be sync'ed first...

The problem is that incomplete `pacman` update when "system" packages are updated. The same thing that is documented [here](https://github.com/git-for-windows/git-sdk-arm64/blob/e190de683341e6bc57cb6cbfea26ef253798a782/update-via-pacman.ps1#L49-L60).

@dennisameling I see you already [sync'ed](https://github.com/git-for-windows/git-sdk-arm64/actions/runs/4108512514), so you're aware of the problem 😁

**Comment by dennisameling** [comment]
I'm signing off for today but have a feeling that the pipeline will work just fine when we retry it now that the `sync` job has run. I just don't dare just starting the pipeline now and then risking it getting stuck while I'm asleep and some VM is burning money 💰 💸

**Comment by dscho** [comment]
@dennisameling yep, let's get a good night's sleep before celebrating a working build (I have no doubt that it'll work) ;-)

**Comment by dennisameling** [comment]
Ok, I had to tweak a few other minor things, and the [build of `mingw-w64-git` succeeded](https://github.com/git-for-windows/git-for-windows-automation/actions/runs/4111902435/jobs/7096174367) after [randomly getting stuck](https://github.com/git-for-windows/git-for-windows-automation/actions/runs/4111715883/jobs/7095771437) and I had to cancel it. I also encountered that exact same issue a few days ago when building locally. It's not consistent. In the vast majority of attempts it works without problems, so let's just keep an eye on it for now.

The "Test-deploy Pacman packages" part [is failing now](https://github.com/git-for-windows/git-for-windows-automation/actions/runs/4111902435/jobs/7096174367#step:19:224) and I'm not sure whether that's related to the `build-installers` package. Maybe it's still missing some binary that this script uses. I could test it locally on an arm64 machine if that's of interest, unless you know right away what might be causing this error 👍🏼

**Comment by dscho** [comment]
> after [randomly getting stuck](https://github.com/git-for-windows/git-for-windows-automation/actions/runs/4111715883/jobs/7095771437)

That could be the code-signing. It has to contact a server for the validated timestamp and that sometimes causes hiccups (but I do not recall seeing any of these issues in the past few years).

> the [build of `mingw-w64-git` succeeded](https://github.com/git-for-windows/git-for-windows-automation/actions/runs/4111902435/jobs/7096174367)

🎉🎉🎉🎉🎉

> The "Test-deploy Pacman packages" part [is failing now](https://github.com/git-for-windows/git-for-windows-automation/actions/runs/4111902435/jobs/7096174367#step:19:224)

Hmm. It says that the `cp` fails because the source and the target "are the same file"... Let me have a look.

**Comment by dscho** [comment]
> > The "Test-deploy Pacman packages" part [is failing now](https://github.com/git-for-windows/git-for-windows-automation/actions/runs/4111902435/jobs/7096174367#step:19:224)
> 
> Hmm. It says that the `cp` fails because the source and the target "are the same file"... Let me have a look.

I am fairly certain that this failure happens in [this line](https://github.com/git-for-windows/build-extra/blob/29b182be06480961a22bd3bff2aefc4d80c5572a/pacman-helper.sh#L680). I remember that the `.db` files were not generated by `repo-add` and that's why that `cp` was needed.

However, that could have changed in the meantime. After all, `pacman` [was updated](https://github.com/git-for-windows/git-sdk-arm64/commit/e190de683341e6bc57cb6cbfea26ef253798a782). Let's see what changed.

*clicketyclick*

https://github.com/msys2/MSYS2-packages/commit/e7424d869af9df472623bfde34b7eb372da97cb0 does not seem as if it could be responsible for this. Let me try a local dry-run and come back to you.

**Comment by dscho** [comment]
I cannot reproduce locally, but I have a hunch that _maybe_ [these lines](https://github.com/git-for-windows/git-sdk-arm64/blob/25187ee25733c6f6aee36c5201cfb645721b0cf5/usr/bin/repo-add#L503-L505) are responsible...

**Comment by dscho** [comment]
Let's see whether I can [debug interactively with tmate](https://github.com/git-for-windows/git-for-windows-automation/actions/runs/4112800458).

**Comment by dennisameling** [comment]
You might as well just run the [`create-azure-self-hosted-runners` workflow](https://github.com/git-for-windows/git-for-windows-automation/actions/workflows/create-azure-self-hosted-runners.yml) manually and RDP into the VM, which might be a bit easier. I can also test locally on my arm64 device later today if that's easier.

**Comment by dscho** [comment]
> You might as well just run the [`create-azure-self-hosted-runners` workflow](https://github.com/git-for-windows/git-for-windows-automation/actions/workflows/create-azure-self-hosted-runners.yml) manually and RDP into the VM, which might be a bit easier. I can also test locally on my arm64 device later today if that's easier.

No, I already tried as manual testing as possible, but cannot replicate the issue. So it's _probably_ something to do with the Actions environment. Maybe symbolic links are enabled or something.

**Comment by dscho** [comment]
Okay, [my give up](https://github.com/git-for-windows/git-for-windows-automation/actions/runs/4113334576/jobs/7099332725#step:7:103). I'll start my Windows/ARM64 VM and hope that I can reproduce there...

**Comment by dscho** [comment]
As I feared, I cannot reproduce in my VM.

**Comment by dscho** [comment]
Aha! I just noticed [this line](https://github.com/git-for-windows/git-for-windows-automation/actions/runs/4113334576/jobs/7099332725#step:6:15). That's the "Maybe symbolic links are enabled" thing: `MSYS=winsymlinks:nativestrict` will do that. I'm just not quite sure where this came from...

**Comment by dennisameling** [comment]
Good catch! That's clearly coming from `setup-git-for-windows-sdk` as it's only set after that CI step. You can find it in the raw `index.js`: https://raw.githubusercontent.com/git-for-windows/setup-git-for-windows-sdk/6697295a149f95f97cb98aff3c2316cf264f7b80/dist/index.js

**Comment by dscho** [comment]
Whoa! But it's not even in `setup-git-for-windows-sdk`! It comes from the `cache` Action. That sucks.

**Comment by dennisameling** [comment]
Looks like that was introduced in `@actions/cache` 3.1.2 (that PR was [merged](https://github.com/git-for-windows/setup-git-for-windows-sdk/pull/571/files#diff-3d2b59189eeedc2d428ddd632e97658fe310f587f7cb63b01f9b98ffc11c0197R1568) recently). Shall we downgrade to 3.1.1 and file a bug report?

**Comment by dscho** [comment]
> Shall we downgrade to 3.1.1 and file a bug report?

I don't want to wait that long, and I don't want to be stuck with an eternally-obsolete dependency.

So I opened https://github.com/git-for-windows/build-extra/pull/477.

**Comment by dennisameling** [comment]
[Let's try again](https://github.com/git-for-windows/git-for-windows-automation/actions/runs/4113939285)! 🤞🏼

**Comment by dennisameling** [comment]
It hang again, so I had to restart. [This time it worked](https://github.com/git-for-windows/git-for-windows-automation/actions/runs/4114193682/jobs/7101244472)! 🎉🎉🎉🎉🎉🎉🎉

Here's a PR to incorporate my temporary fixes into the `build-and-deploy` workflow moving forward: https://github.com/git-for-windows/git-for-windows-automation/pull/25

**Comment by dennisameling** [comment]
> @dennisameling do we need anything else to support `build-installers`/`aarch64` in this Action? If not, I'll gladly release v1.8.0 with the news!

I think we're good to release v1.8.0 now, right? 😊

**Comment by dscho** [comment]
> > @dennisameling do we need anything else to support `build-installers`/`aarch64` in this Action? If not, I'll gladly release v1.8.0 with the news!
> 
> I think we're good to release v1.8.0 now, right? 😊

Yes!!!

**Comment by dscho** [comment]
https://github.com/git-for-windows/setup-git-for-windows-sdk/releases/tag/v1.8.0 🎉

**Pull request merged**
