### PR TITLE
Accelerate via @actions/cache

### PR DESCRIPTION
**Pull request by dscho**
This change makes this Action truly useful: the first time we try to get a given build artifact, it _will_ be downloaded from Azure Pipelines. But then it will be cached. And subsequent attempts will use the cached version and be a lot faster!

### CODE REVIEW

**Comment by dscho** [comment]
@dennisameling I would also _love_ to have your 👀 over this PR...

**Comment by dscho** [comment]
I am currently testing this by running a full matrix here: https://github.com/dscho/setup-git-for-windows-sdk/runs/1925713769?check_suite_focus=true. Once that run is done (and so far, it looks pretty good, having cached 4 out of the 6 artifacts), I will push a new commit to the `test` branch that triggers another run: this one should use the cached artifacts and demonstrate just how much faster things become this way.

**Comment by dscho** [comment]
Wow, caching is not exactly cheap, either: [the full 32-bit SDK takes ~2m45s to cache 914MB](https://github.com/dscho/setup-git-for-windows-sdk/runs/1925713816?check_suite_focus=true#step:2:37)... in contrast, [it only takes ~15s to cache the ~75MB of `git-sdk-64-minimal`](https://github.com/dscho/setup-git-for-windows-sdk/runs/1925713724?check_suite_focus=true#step:2:19) (hit the gear on the upper right to "Show timestamps").

**Comment by dscho** [comment]
Whoa, [it takes ~5m20s to cache the 64-bit full SDK as a 1300MB `.tar.gz` file...](https://github.com/dscho/setup-git-for-windows-sdk/runs/1925713797?check_suite_focus=true#step:2:48).

**Comment by dscho** [comment]
Yes!!! The [subsequent run](https://github.com/dscho/setup-git-for-windows-sdk/actions/runs/577685295) manages to restore the minimal SDK [in 10s](https://github.com/dscho/setup-git-for-windows-sdk/runs/1925803936?check_suite_focus=true) instead of [the 1m4s in the uncached case](https://github.com/dscho/setup-git-for-windows-sdk/runs/1925713724?check_suite_focus=true).

For the `git-artifacts.yml` workflow, the most interesting comparison is the `build-installers` one: [1m](https://github.com/dscho/setup-git-for-windows-sdk/runs/1925803966?check_suite_focus=true) vs [~5m30s](https://github.com/dscho/setup-git-for-windows-sdk/runs/1925713769?check_suite_focus=true).

In contrast, the full SDKs seem not to benefit all that much. A [run from yesterday](https://github.com/git-for-windows/setup-git-for-windows-sdk/runs/1923458530?check_suite_focus=true) (without caching the just-downloaded artifacts) clocked the 32-bit and 64-bit full SDK at [~6m](https://github.com/git-for-windows/setup-git-for-windows-sdk/runs/1923458530?check_suite_focus=true) and [~8m20s](https://github.com/git-for-windows/setup-git-for-windows-sdk/runs/1923458514?check_suite_focus=true), respectively. When restoring them from cache, the numbers are [~5m](https://github.com/dscho/setup-git-for-windows-sdk/runs/1925804036?check_suite_focus=true) and [~8m15s](https://github.com/dscho/setup-git-for-windows-sdk/runs/1925804008?check_suite_focus=true), respectively.

Given these findings, I think we will want to disable the cache for the full SDKs by default because it does not really seem to give us a big bang for the buck.

**Comment by dscho** [comment]
This PR is now based on #9, which should be merged first.

**Comment by dscho** [comment]
And [here](https://github.com/dscho/setup-git-for-windows-sdk/runs/1926135131?check_suite_focus=true) is a run that exercises the full supported flavor/architecture matrix with the default caching.

I think this is good to go now.

**Comment by dennisameling** [comment]
This looks great, but I'm not sure about one thing...

> When restoring them from cache, the numbers are ~5m and ~8m15s, respectively.

For [`x86_64`](https://github.com/dscho/setup-git-for-windows-sdk/runs/1925804008?check_suite_focus=true), the cache size looks rather large to me: `Cache Size: ~1300 MB (1363005456 B)`, compared to the [full download](https://github.com/dscho/setup-git-for-windows-sdk/runs/1926135110?check_suite_focus=true) from Azure Pipelines (~500M):

```
100  497M    0  497M    0     0  14.1M      0 --:--:--  0:00:35 --:--:-- 15.8M
unzipping C:/git-sdk-64-full-sdk/tmpz0AltS/artifacts.zip
```

Are you sure that's correct?

**Comment by dscho** [comment]
> > When restoring them from cache, the numbers are ~5m and ~8m15s, respectively.
> 
> For [`x86_64`](https://github.com/dscho/setup-git-for-windows-sdk/runs/1925804008?check_suite_focus=true), the cache size looks rather large to me: `Cache Size: ~1300 MB (1363005456 B)`, compared to the [full download](https://github.com/dscho/setup-git-for-windows-sdk/runs/1926135110?check_suite_focus=true) from Azure Pipelines (~500M):
> 
> ```
> 100  497M    0  497M    0     0  14.1M      0 --:--:--  0:00:35 --:--:-- 15.8M
> unzipping C:/git-sdk-64-full-sdk/tmpz0AltS/artifacts.zip
> ```
> 
> Are you sure that's correct?

Yes, that's correct. The `full` SDK is actually not just a `.zip` file, it is a `.tar.xz` file _within_ a `.zip` file. That's a deviation from all the other flavors, specifically so that the bandwidth is used more efficiently (I tried to strike a balance between download and extraction time).

**Comment by dscho** [comment]
Rebased (and regenerated `dist/`), to avoid the merge conflicts in `dist/index.js`.

**Comment by dscho** [comment]
> This looks great, but I'm not sure about one thing...

With the question why 500MB are equivalent to 1,300MB out of the way, I interpret this as your :+1: to merging this ;-)

**Pull request merged**
